=== Boppel/HDM-repo/sda/sda rush/xml/book_scheme.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1">
 
    <xs:element name="book">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element ref="chapter" minOccurs="1" maxOccurs="unbounded"></xs:element>          
            </xs:sequence>
        </xs:complexType>        
    </xs:element>
    
    <xs:element name="title" type="xs:string"></xs:element>
    
    <xs:element name="chapter">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="paragraph" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== Boppel/HDM-repo/sda/sda rush/xml/book.xml
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="book_scheme.xsd">
    
    <title>A Hitchhikers Guide to the Universe</title>
    
    <chapter>
        <title>Never forget a towel</title>
        <paragraph>Towels are important because they can dry you.</paragraph>
    </chapter>
    
    <chapter>
        <title>Seriously, never forget the towel</title>
        <paragraph>Towlie Towlie Towlie Towlie Towlie </paragraph>
    </chapter>
</book>
