=== Boppel/HDM-repo/sda/test8/xml/customer_scheme.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1">
    
    <xs:element name="customer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" minOccurs="1"/>
                <xs:element name="phoneNumber" type="xs:string" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="customer" maxOccurs="unbounded"/>
                <xs:element ref="invoice" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="customerId">
            <xs:selector xpath="customer"></xs:selector>
            <xs:field xpath="@id"></xs:field>
        </xs:key>
        
        <xs:keyref refer="customerId" name="customerToInvoice">
            <xs:selector xpath="invoice"></xs:selector>
            <xs:field xpath="@customerId"></xs:field>
        </xs:keyref>
    </xs:element>
    
    <xs:element name="invoice">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="amount" type="money" minOccurs="1"/>
                <xs:element name="status" type="status" minOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="customerId" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="money">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="status">
        <xs:restriction base="xs:string">
            <xs:enumeration value="open"/>
            <xs:enumeration value="due"/>
            <xs:enumeration value="cleared"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== Boppel/HDM-repo/sda/sda rush/xml/customer.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="customer_scheme.xsd">
    
    <customer id="1">
        <name>Adolf</name>
    </customer>
    
    <customer id="2">
        <name>Hermann</name>
    </customer>
    
    <customer id="3">
        <name>Josef</name>
    </customer>
    
    <invoice customerId="1">
        <amount>100.00</amount>
        <status>open</status>
    </invoice>
    
    <invoice customerId="2">
        <amount>123.45</amount>
        <status>due</status>
    </invoice>
    
    <invoice customerId="3">
        <amount>666</amount>
        <status>cleared</status>
    </invoice>

</data>
