=== Boppel/HDM-repo/sda/test4/person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1">
    
    
    <xs:element name="persons">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="person" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    <xs:element name="person">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="firstName"/>
                <xs:element name="lastName"/>
                <xs:element name="phone" minOccurs="0"/>
                <xs:element name="email" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:int" use="optional"/>
        </xs:complexType>
          
    </xs:element>
    
</xs:schema>

=== Boppel/HDM-repo/Structured Data and Applications/test4/personData.xml
<?xml version="1.0" encoding="UTF-8"?>

<persons 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="person.xsd">
    
    <person id="23">
        <firstName>Sue</firstName>
        <lastName>White</lastName>
        <phone>322-33434</phone>
    </person>    

    <person id="27">
        <firstName>Sue</firstName>
        <lastName>White</lastName>
        <phone>323-433453</phone>
        <email>white@lispy.com</email>
    </person>
    
    <person>
        <firstName>James</firstName>
        <lastName>Brown</lastName>
    </person>
    
    <person id="30"> 
        <firstName>Linda</firstName>
        <lastName>Dempsey</lastName>
    </person>
    
</persons>
